enable_disqus:    false
enable_analytics: false

highlighter: rouge
permalink:   pretty

exclude:
  - node_modules/
  - nbproject/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "artigo"

# for sitemap
url: http://www.devfuria.com.br